"""empty message

Revision ID: 1ac9dec977f6
Revises: e2125ba675ae
Create Date: 2023-07-09 05:24:24.520492

"""


# revision identifiers, used by Alembic.
revision = "1ac9dec977f6"
down_revision = "e2125ba675ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
