"""empty message

Revision ID: 1b844dfce1f3
Revises: 1ac9dec977f6
Create Date: 2023-07-09 05:24:28.233464

"""


# revision identifiers, used by Alembic.
revision = "1b844dfce1f3"
down_revision = "1ac9dec977f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
