"""empty message

Revision ID: 73c6b06a4275
Revises: d4867f3a4c0a
Create Date: 2023-07-06 04:09:42.039468

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "73c6b06a4275"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
