"""empty message

Revision ID: 7a90bd595da1
Revises: a3fbdc17f914
Create Date: 2023-07-08 22:19:43.267456

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a90bd595da1"
down_revision = "a3fbdc17f914"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_quote_tags", table_name="quote")
    op.drop_index("ix_quote_text", table_name="quote")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_quote_text", "quote", ["text"], unique=False)
    op.create_index("ix_quote_tags", "quote", ["tags"], unique=False)
    # ### end Alembic commands ###
