"""empty message

Revision ID: a3fbdc17f914
Revises: 532274103aee
Create Date: 2023-07-08 21:30:43.979209

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a3fbdc17f914"
down_revision = "532274103aee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("tags", sa.String(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("categories_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["quote_author.id"],
        ),
        sa.ForeignKeyConstraint(
            ["categories_id"],
            ["quote_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quote_id"), "quote", ["id"], unique=False)
    op.create_index(op.f("ix_quote_tags"), "quote", ["tags"], unique=False)
    op.create_index(op.f("ix_quote_text"), "quote", ["text"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quote_text"), table_name="quote")
    op.drop_index(op.f("ix_quote_tags"), table_name="quote")
    op.drop_index(op.f("ix_quote_id"), table_name="quote")
    op.drop_table("quote")
    # ### end Alembic commands ###
