"""empty message

Revision ID: e2125ba675ae
Revises: 7a90bd595da1
Create Date: 2023-07-09 05:21:43.463364

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2125ba675ae"
down_revision = "7a90bd595da1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_quote_tags"), "quote", ["tags"], unique=False)
    op.create_index(op.f("ix_quote_text"), "quote", ["text"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quote_text"), table_name="quote")
    op.drop_index(op.f("ix_quote_tags"), table_name="quote")
    # ### end Alembic commands ###
