"""empty message

Revision ID: fc69d2b0cf1b
Revises: aff7b781d5b5
Create Date: 2023-07-11 07:07:09.012939

"""


# revision identifiers, used by Alembic.
revision = "fc69d2b0cf1b"
down_revision = "aff7b781d5b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
