repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        - id: fix-byte-order-marker
        - id: check-yaml
        - id: end-of-file-fixer
        - id: requirements-txt-fixer
        - id: trailing-whitespace
          args: [--markdown-linebreak-ext=md]

# -   repo: https://github.com/myint/autoflake
#     rev: v2.2.0
#     hooks:
#         - id: autoflake
#           args:
#             - --in-place
#             - --remove-all-unused-imports
#             - --remove-unused-variables
#             - --ignore-init-module-imports


# -   repo: https://github.com/psf/black
#     rev: 23.1.0
#     hooks:
#     -   id: black

# -   repo: https://github.com/pycqa/isort
#     rev: 5.12.0
#     hooks:
#         - id: isort
#           name: isort (python)
