FROM bitnami/python:3.10

# Install Poetry
RUN pip install poetry

WORKDIR /app

# Copy only dependencies definition to the docker image
COPY pyproject.toml poetry.lock /app/

# Install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi

# Copy the rest of the code
COPY . /app

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
