name: CodeCoverage

on:
  push:
    branches: [ "main", "stag", "dev" ]
  pull_request:
    branches: [ "main", "stag", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      working-directory: iquote

    - name: Test with pytest
      run: |
        poetry shell
        make run-test
        make run-test-cov
      working-directory: iquote

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # not required for public repos
        files: iquote/.coverage.xml  # path to coverage file
        fail_ci_if_error: true  # optional (default = false)
