name: SonarCloud

on:
  push:
    branches: [ "main", "stag", "dev" ]
  pull_request:
    branches: [ "main", "stag", "dev" ]


jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    services:
      postgres:
        image: 'bitnami/postgresql:14.8.0'
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: iquote_fastapi
        ports:
          - 5432:5432
      #   options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
        working-directory: iquote

      - name: Test with pytest
        run: |
          cp .env.test .env
          poetry run make db-prestart
          poetry run make run-test
          poetry run make run-test-cov
        working-directory: iquote

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: nunenuh_iquote-fastapi
